apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 4
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
    #- type: Resource
    #  resource:
    #    name: memory
    #    target:
    #      type: Utilization
    #      averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 20
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
      - type: Percent
        value: 80
        periodSeconds: 20
      - type: Pods
        value: 2
        periodSeconds: 60
 